// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs_notify.proto

#ifndef PROTOBUF_cs_5fnotify_2eproto__INCLUDED
#define PROTOBUF_cs_5fnotify_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ProtoCs {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_cs_5fnotify_2eproto();
void protobuf_AssignDesc_cs_5fnotify_2eproto();
void protobuf_ShutdownFile_cs_5fnotify_2eproto();

class RoleInfoNtf;
class CityInfo;
class CityListNtf;
class ServerKickOffNtf;

// ===================================================================

class RoleInfoNtf : public ::google::protobuf::Message {
 public:
  RoleInfoNtf();
  virtual ~RoleInfoNtf();

  RoleInfoNtf(const RoleInfoNtf& from);

  inline RoleInfoNtf& operator=(const RoleInfoNtf& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoleInfoNtf& default_instance();

  void Swap(RoleInfoNtf* other);

  // implements Message ----------------------------------------------

  RoleInfoNtf* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RoleInfoNtf& from);
  void MergeFrom(const RoleInfoNtf& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 money = 1;
  inline bool has_money() const;
  inline void clear_money();
  static const int kMoneyFieldNumber = 1;
  inline ::google::protobuf::int32 money() const;
  inline void set_money(::google::protobuf::int32 value);

  // optional int32 level = 2;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 2;
  inline ::google::protobuf::int32 level() const;
  inline void set_level(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ProtoCs.RoleInfoNtf)
 private:
  inline void set_has_money();
  inline void clear_has_money();
  inline void set_has_level();
  inline void clear_has_level();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 money_;
  ::google::protobuf::int32 level_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_cs_5fnotify_2eproto();
  friend void protobuf_AssignDesc_cs_5fnotify_2eproto();
  friend void protobuf_ShutdownFile_cs_5fnotify_2eproto();

  void InitAsDefaultInstance();
  static RoleInfoNtf* default_instance_;
};
// -------------------------------------------------------------------

class CityInfo : public ::google::protobuf::Message {
 public:
  CityInfo();
  virtual ~CityInfo();

  CityInfo(const CityInfo& from);

  inline CityInfo& operator=(const CityInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CityInfo& default_instance();

  void Swap(CityInfo* other);

  // implements Message ----------------------------------------------

  CityInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CityInfo& from);
  void MergeFrom(const CityInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional int32 population = 2;
  inline bool has_population() const;
  inline void clear_population();
  static const int kPopulationFieldNumber = 2;
  inline ::google::protobuf::int32 population() const;
  inline void set_population(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ProtoCs.CityInfo)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_population();
  inline void clear_has_population();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 population_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_cs_5fnotify_2eproto();
  friend void protobuf_AssignDesc_cs_5fnotify_2eproto();
  friend void protobuf_ShutdownFile_cs_5fnotify_2eproto();

  void InitAsDefaultInstance();
  static CityInfo* default_instance_;
};
// -------------------------------------------------------------------

class CityListNtf : public ::google::protobuf::Message {
 public:
  CityListNtf();
  virtual ~CityListNtf();

  CityListNtf(const CityListNtf& from);

  inline CityListNtf& operator=(const CityListNtf& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CityListNtf& default_instance();

  void Swap(CityListNtf* other);

  // implements Message ----------------------------------------------

  CityListNtf* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CityListNtf& from);
  void MergeFrom(const CityListNtf& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ProtoCs.CityInfo city_list = 1;
  inline int city_list_size() const;
  inline void clear_city_list();
  static const int kCityListFieldNumber = 1;
  inline const ::ProtoCs::CityInfo& city_list(int index) const;
  inline ::ProtoCs::CityInfo* mutable_city_list(int index);
  inline ::ProtoCs::CityInfo* add_city_list();
  inline const ::google::protobuf::RepeatedPtrField< ::ProtoCs::CityInfo >&
      city_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProtoCs::CityInfo >*
      mutable_city_list();

  // @@protoc_insertion_point(class_scope:ProtoCs.CityListNtf)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::ProtoCs::CityInfo > city_list_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_cs_5fnotify_2eproto();
  friend void protobuf_AssignDesc_cs_5fnotify_2eproto();
  friend void protobuf_ShutdownFile_cs_5fnotify_2eproto();

  void InitAsDefaultInstance();
  static CityListNtf* default_instance_;
};
// -------------------------------------------------------------------

class ServerKickOffNtf : public ::google::protobuf::Message {
 public:
  ServerKickOffNtf();
  virtual ~ServerKickOffNtf();

  ServerKickOffNtf(const ServerKickOffNtf& from);

  inline ServerKickOffNtf& operator=(const ServerKickOffNtf& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerKickOffNtf& default_instance();

  void Swap(ServerKickOffNtf* other);

  // implements Message ----------------------------------------------

  ServerKickOffNtf* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerKickOffNtf& from);
  void MergeFrom(const ServerKickOffNtf& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ProtoCs.ServerKickOffNtf)
 private:
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_cs_5fnotify_2eproto();
  friend void protobuf_AssignDesc_cs_5fnotify_2eproto();
  friend void protobuf_ShutdownFile_cs_5fnotify_2eproto();

  void InitAsDefaultInstance();
  static ServerKickOffNtf* default_instance_;
};
// ===================================================================


// ===================================================================

// RoleInfoNtf

// optional int32 money = 1;
inline bool RoleInfoNtf::has_money() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RoleInfoNtf::set_has_money() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RoleInfoNtf::clear_has_money() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RoleInfoNtf::clear_money() {
  money_ = 0;
  clear_has_money();
}
inline ::google::protobuf::int32 RoleInfoNtf::money() const {
  return money_;
}
inline void RoleInfoNtf::set_money(::google::protobuf::int32 value) {
  set_has_money();
  money_ = value;
}

// optional int32 level = 2;
inline bool RoleInfoNtf::has_level() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RoleInfoNtf::set_has_level() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RoleInfoNtf::clear_has_level() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RoleInfoNtf::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 RoleInfoNtf::level() const {
  return level_;
}
inline void RoleInfoNtf::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
}

// -------------------------------------------------------------------

// CityInfo

// optional int32 id = 1;
inline bool CityInfo::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CityInfo::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CityInfo::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CityInfo::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 CityInfo::id() const {
  return id_;
}
inline void CityInfo::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// optional int32 population = 2;
inline bool CityInfo::has_population() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CityInfo::set_has_population() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CityInfo::clear_has_population() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CityInfo::clear_population() {
  population_ = 0;
  clear_has_population();
}
inline ::google::protobuf::int32 CityInfo::population() const {
  return population_;
}
inline void CityInfo::set_population(::google::protobuf::int32 value) {
  set_has_population();
  population_ = value;
}

// -------------------------------------------------------------------

// CityListNtf

// repeated .ProtoCs.CityInfo city_list = 1;
inline int CityListNtf::city_list_size() const {
  return city_list_.size();
}
inline void CityListNtf::clear_city_list() {
  city_list_.Clear();
}
inline const ::ProtoCs::CityInfo& CityListNtf::city_list(int index) const {
  return city_list_.Get(index);
}
inline ::ProtoCs::CityInfo* CityListNtf::mutable_city_list(int index) {
  return city_list_.Mutable(index);
}
inline ::ProtoCs::CityInfo* CityListNtf::add_city_list() {
  return city_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoCs::CityInfo >&
CityListNtf::city_list() const {
  return city_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoCs::CityInfo >*
CityListNtf::mutable_city_list() {
  return &city_list_;
}

// -------------------------------------------------------------------

// ServerKickOffNtf

// optional int32 type = 1;
inline bool ServerKickOffNtf::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServerKickOffNtf::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServerKickOffNtf::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServerKickOffNtf::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 ServerKickOffNtf::type() const {
  return type_;
}
inline void ServerKickOffNtf::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtoCs

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cs_5fnotify_2eproto__INCLUDED
