// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ss_msg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ss_msg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ProtoSs {

namespace {

const ::google::protobuf::Descriptor* Head_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Head_reflection_ = NULL;
const ::google::protobuf::Descriptor* Msg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Msg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ss_5fmsg_2eproto() {
  protobuf_AddDesc_ss_5fmsg_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ss_msg.proto");
  GOOGLE_CHECK(file != NULL);
  Head_descriptor_ = file->message_type(0);
  static const int Head_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Head, cmd_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Head, ret_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Head, seq_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Head, player_idx_),
  };
  Head_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Head_descriptor_,
      Head::default_instance_,
      Head_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Head, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Head, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Head));
  Msg_descriptor_ = file->message_type(1);
  static const int Msg_offsets_[13] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg, head_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg, account_reg_req_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg, account_reg_res_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg, bind_account_req_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg, bind_account_res_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg, edit_password_req_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg, edit_password_res_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg, account_verify_req_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg, account_verify_res_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg, get_player_data_req_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg, get_player_data_res_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg, set_player_data_req_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg, set_player_data_res_),
  };
  Msg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Msg_descriptor_,
      Msg::default_instance_,
      Msg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Msg));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ss_5fmsg_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Head_descriptor_, &Head::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Msg_descriptor_, &Msg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ss_5fmsg_2eproto() {
  delete Head::default_instance_;
  delete Head_reflection_;
  delete Msg::default_instance_;
  delete Msg_reflection_;
}

void protobuf_AddDesc_ss_5fmsg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::ProtoSs::protobuf_AddDesc_ss_5fdata_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014ss_msg.proto\022\007ProtoSs\032\rss_data.proto\"A"
    "\n\004Head\022\013\n\003cmd\030\001 \001(\005\022\013\n\003ret\030\002 \001(\005\022\013\n\003seq\030"
    "\003 \001(\004\022\022\n\nplayer_idx\030\004 \001(\005\"\242\005\n\003Msg\022\033\n\004hea"
    "d\030\001 \001(\0132\r.ProtoSs.Head\022/\n\017account_reg_re"
    "q\030\013 \001(\0132\026.ProtoSs.AccountRegReq\022/\n\017accou"
    "nt_reg_res\030\014 \001(\0132\026.ProtoSs.AccountRegRes"
    "\0221\n\020bind_account_req\030\r \001(\0132\027.ProtoSs.Bin"
    "dAccountReq\0221\n\020bind_account_res\030\016 \001(\0132\027."
    "ProtoSs.BindAccountRes\0223\n\021edit_password_"
    "req\030\017 \001(\0132\030.ProtoSs.EditPasswordReq\0223\n\021e"
    "dit_password_res\030\020 \001(\0132\030.ProtoSs.EditPas"
    "swordRes\0225\n\022account_verify_req\030\021 \001(\0132\031.P"
    "rotoSs.AccountVerifyReq\0225\n\022account_verif"
    "y_res\030\022 \001(\0132\031.ProtoSs.AccountVerifyRes\0226"
    "\n\023get_player_data_req\030\023 \001(\0132\031.ProtoSs.Ge"
    "tPlayerDataReq\0226\n\023get_player_data_res\030\024 "
    "\001(\0132\031.ProtoSs.GetPlayerDataRes\0226\n\023set_pl"
    "ayer_data_req\030\025 \001(\0132\031.ProtoSs.SetPlayerD"
    "ataReq\0226\n\023set_player_data_res\030\026 \001(\0132\031.Pr"
    "otoSs.SetPlayerDataRes", 782);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ss_msg.proto", &protobuf_RegisterTypes);
  Head::default_instance_ = new Head();
  Msg::default_instance_ = new Msg();
  Head::default_instance_->InitAsDefaultInstance();
  Msg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ss_5fmsg_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ss_5fmsg_2eproto {
  StaticDescriptorInitializer_ss_5fmsg_2eproto() {
    protobuf_AddDesc_ss_5fmsg_2eproto();
  }
} static_descriptor_initializer_ss_5fmsg_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Head::kCmdFieldNumber;
const int Head::kRetFieldNumber;
const int Head::kSeqFieldNumber;
const int Head::kPlayerIdxFieldNumber;
#endif  // !_MSC_VER

Head::Head()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Head::InitAsDefaultInstance() {
}

Head::Head(const Head& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Head::SharedCtor() {
  _cached_size_ = 0;
  cmd_ = 0;
  ret_ = 0;
  seq_ = GOOGLE_ULONGLONG(0);
  player_idx_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Head::~Head() {
  SharedDtor();
}

void Head::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Head::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Head::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Head_descriptor_;
}

const Head& Head::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ss_5fmsg_2eproto();
  return *default_instance_;
}

Head* Head::default_instance_ = NULL;

Head* Head::New() const {
  return new Head;
}

void Head::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    cmd_ = 0;
    ret_ = 0;
    seq_ = GOOGLE_ULONGLONG(0);
    player_idx_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Head::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 cmd = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cmd_)));
          set_has_cmd();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_ret;
        break;
      }

      // optional int32 ret = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_ret:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ret_)));
          set_has_ret();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_seq;
        break;
      }

      // optional uint64 seq = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_seq:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &seq_)));
          set_has_seq();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_player_idx;
        break;
      }

      // optional int32 player_idx = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_player_idx:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &player_idx_)));
          set_has_player_idx();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Head::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 cmd = 1;
  if (has_cmd()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->cmd(), output);
  }

  // optional int32 ret = 2;
  if (has_ret()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->ret(), output);
  }

  // optional uint64 seq = 3;
  if (has_seq()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->seq(), output);
  }

  // optional int32 player_idx = 4;
  if (has_player_idx()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->player_idx(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Head::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 cmd = 1;
  if (has_cmd()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->cmd(), target);
  }

  // optional int32 ret = 2;
  if (has_ret()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->ret(), target);
  }

  // optional uint64 seq = 3;
  if (has_seq()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->seq(), target);
  }

  // optional int32 player_idx = 4;
  if (has_player_idx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->player_idx(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Head::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 cmd = 1;
    if (has_cmd()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->cmd());
    }

    // optional int32 ret = 2;
    if (has_ret()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->ret());
    }

    // optional uint64 seq = 3;
    if (has_seq()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->seq());
    }

    // optional int32 player_idx = 4;
    if (has_player_idx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->player_idx());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Head::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Head* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Head*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Head::MergeFrom(const Head& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_cmd()) {
      set_cmd(from.cmd());
    }
    if (from.has_ret()) {
      set_ret(from.ret());
    }
    if (from.has_seq()) {
      set_seq(from.seq());
    }
    if (from.has_player_idx()) {
      set_player_idx(from.player_idx());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Head::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Head::CopyFrom(const Head& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Head::IsInitialized() const {

  return true;
}

void Head::Swap(Head* other) {
  if (other != this) {
    std::swap(cmd_, other->cmd_);
    std::swap(ret_, other->ret_);
    std::swap(seq_, other->seq_);
    std::swap(player_idx_, other->player_idx_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Head::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Head_descriptor_;
  metadata.reflection = Head_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Msg::kHeadFieldNumber;
const int Msg::kAccountRegReqFieldNumber;
const int Msg::kAccountRegResFieldNumber;
const int Msg::kBindAccountReqFieldNumber;
const int Msg::kBindAccountResFieldNumber;
const int Msg::kEditPasswordReqFieldNumber;
const int Msg::kEditPasswordResFieldNumber;
const int Msg::kAccountVerifyReqFieldNumber;
const int Msg::kAccountVerifyResFieldNumber;
const int Msg::kGetPlayerDataReqFieldNumber;
const int Msg::kGetPlayerDataResFieldNumber;
const int Msg::kSetPlayerDataReqFieldNumber;
const int Msg::kSetPlayerDataResFieldNumber;
#endif  // !_MSC_VER

Msg::Msg()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Msg::InitAsDefaultInstance() {
  head_ = const_cast< ::ProtoSs::Head*>(&::ProtoSs::Head::default_instance());
  account_reg_req_ = const_cast< ::ProtoSs::AccountRegReq*>(&::ProtoSs::AccountRegReq::default_instance());
  account_reg_res_ = const_cast< ::ProtoSs::AccountRegRes*>(&::ProtoSs::AccountRegRes::default_instance());
  bind_account_req_ = const_cast< ::ProtoSs::BindAccountReq*>(&::ProtoSs::BindAccountReq::default_instance());
  bind_account_res_ = const_cast< ::ProtoSs::BindAccountRes*>(&::ProtoSs::BindAccountRes::default_instance());
  edit_password_req_ = const_cast< ::ProtoSs::EditPasswordReq*>(&::ProtoSs::EditPasswordReq::default_instance());
  edit_password_res_ = const_cast< ::ProtoSs::EditPasswordRes*>(&::ProtoSs::EditPasswordRes::default_instance());
  account_verify_req_ = const_cast< ::ProtoSs::AccountVerifyReq*>(&::ProtoSs::AccountVerifyReq::default_instance());
  account_verify_res_ = const_cast< ::ProtoSs::AccountVerifyRes*>(&::ProtoSs::AccountVerifyRes::default_instance());
  get_player_data_req_ = const_cast< ::ProtoSs::GetPlayerDataReq*>(&::ProtoSs::GetPlayerDataReq::default_instance());
  get_player_data_res_ = const_cast< ::ProtoSs::GetPlayerDataRes*>(&::ProtoSs::GetPlayerDataRes::default_instance());
  set_player_data_req_ = const_cast< ::ProtoSs::SetPlayerDataReq*>(&::ProtoSs::SetPlayerDataReq::default_instance());
  set_player_data_res_ = const_cast< ::ProtoSs::SetPlayerDataRes*>(&::ProtoSs::SetPlayerDataRes::default_instance());
}

Msg::Msg(const Msg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Msg::SharedCtor() {
  _cached_size_ = 0;
  head_ = NULL;
  account_reg_req_ = NULL;
  account_reg_res_ = NULL;
  bind_account_req_ = NULL;
  bind_account_res_ = NULL;
  edit_password_req_ = NULL;
  edit_password_res_ = NULL;
  account_verify_req_ = NULL;
  account_verify_res_ = NULL;
  get_player_data_req_ = NULL;
  get_player_data_res_ = NULL;
  set_player_data_req_ = NULL;
  set_player_data_res_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Msg::~Msg() {
  SharedDtor();
}

void Msg::SharedDtor() {
  if (this != default_instance_) {
    delete head_;
    delete account_reg_req_;
    delete account_reg_res_;
    delete bind_account_req_;
    delete bind_account_res_;
    delete edit_password_req_;
    delete edit_password_res_;
    delete account_verify_req_;
    delete account_verify_res_;
    delete get_player_data_req_;
    delete get_player_data_res_;
    delete set_player_data_req_;
    delete set_player_data_res_;
  }
}

void Msg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Msg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Msg_descriptor_;
}

const Msg& Msg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ss_5fmsg_2eproto();
  return *default_instance_;
}

Msg* Msg::default_instance_ = NULL;

Msg* Msg::New() const {
  return new Msg;
}

void Msg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_head()) {
      if (head_ != NULL) head_->::ProtoSs::Head::Clear();
    }
    if (has_account_reg_req()) {
      if (account_reg_req_ != NULL) account_reg_req_->::ProtoSs::AccountRegReq::Clear();
    }
    if (has_account_reg_res()) {
      if (account_reg_res_ != NULL) account_reg_res_->::ProtoSs::AccountRegRes::Clear();
    }
    if (has_bind_account_req()) {
      if (bind_account_req_ != NULL) bind_account_req_->::ProtoSs::BindAccountReq::Clear();
    }
    if (has_bind_account_res()) {
      if (bind_account_res_ != NULL) bind_account_res_->::ProtoSs::BindAccountRes::Clear();
    }
    if (has_edit_password_req()) {
      if (edit_password_req_ != NULL) edit_password_req_->::ProtoSs::EditPasswordReq::Clear();
    }
    if (has_edit_password_res()) {
      if (edit_password_res_ != NULL) edit_password_res_->::ProtoSs::EditPasswordRes::Clear();
    }
    if (has_account_verify_req()) {
      if (account_verify_req_ != NULL) account_verify_req_->::ProtoSs::AccountVerifyReq::Clear();
    }
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (has_account_verify_res()) {
      if (account_verify_res_ != NULL) account_verify_res_->::ProtoSs::AccountVerifyRes::Clear();
    }
    if (has_get_player_data_req()) {
      if (get_player_data_req_ != NULL) get_player_data_req_->::ProtoSs::GetPlayerDataReq::Clear();
    }
    if (has_get_player_data_res()) {
      if (get_player_data_res_ != NULL) get_player_data_res_->::ProtoSs::GetPlayerDataRes::Clear();
    }
    if (has_set_player_data_req()) {
      if (set_player_data_req_ != NULL) set_player_data_req_->::ProtoSs::SetPlayerDataReq::Clear();
    }
    if (has_set_player_data_res()) {
      if (set_player_data_res_ != NULL) set_player_data_res_->::ProtoSs::SetPlayerDataRes::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Msg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .ProtoSs.Head head = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_head()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(90)) goto parse_account_reg_req;
        break;
      }

      // optional .ProtoSs.AccountRegReq account_reg_req = 11;
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_account_reg_req:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_account_reg_req()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(98)) goto parse_account_reg_res;
        break;
      }

      // optional .ProtoSs.AccountRegRes account_reg_res = 12;
      case 12: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_account_reg_res:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_account_reg_res()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(106)) goto parse_bind_account_req;
        break;
      }

      // optional .ProtoSs.BindAccountReq bind_account_req = 13;
      case 13: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_bind_account_req:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_bind_account_req()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(114)) goto parse_bind_account_res;
        break;
      }

      // optional .ProtoSs.BindAccountRes bind_account_res = 14;
      case 14: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_bind_account_res:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_bind_account_res()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(122)) goto parse_edit_password_req;
        break;
      }

      // optional .ProtoSs.EditPasswordReq edit_password_req = 15;
      case 15: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_edit_password_req:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_edit_password_req()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(130)) goto parse_edit_password_res;
        break;
      }

      // optional .ProtoSs.EditPasswordRes edit_password_res = 16;
      case 16: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_edit_password_res:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_edit_password_res()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(138)) goto parse_account_verify_req;
        break;
      }

      // optional .ProtoSs.AccountVerifyReq account_verify_req = 17;
      case 17: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_account_verify_req:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_account_verify_req()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(146)) goto parse_account_verify_res;
        break;
      }

      // optional .ProtoSs.AccountVerifyRes account_verify_res = 18;
      case 18: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_account_verify_res:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_account_verify_res()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(154)) goto parse_get_player_data_req;
        break;
      }

      // optional .ProtoSs.GetPlayerDataReq get_player_data_req = 19;
      case 19: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_get_player_data_req:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_get_player_data_req()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(162)) goto parse_get_player_data_res;
        break;
      }

      // optional .ProtoSs.GetPlayerDataRes get_player_data_res = 20;
      case 20: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_get_player_data_res:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_get_player_data_res()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(170)) goto parse_set_player_data_req;
        break;
      }

      // optional .ProtoSs.SetPlayerDataReq set_player_data_req = 21;
      case 21: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_set_player_data_req:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_set_player_data_req()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(178)) goto parse_set_player_data_res;
        break;
      }

      // optional .ProtoSs.SetPlayerDataRes set_player_data_res = 22;
      case 22: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_set_player_data_res:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_set_player_data_res()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Msg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .ProtoSs.Head head = 1;
  if (has_head()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->head(), output);
  }

  // optional .ProtoSs.AccountRegReq account_reg_req = 11;
  if (has_account_reg_req()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, this->account_reg_req(), output);
  }

  // optional .ProtoSs.AccountRegRes account_reg_res = 12;
  if (has_account_reg_res()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, this->account_reg_res(), output);
  }

  // optional .ProtoSs.BindAccountReq bind_account_req = 13;
  if (has_bind_account_req()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      13, this->bind_account_req(), output);
  }

  // optional .ProtoSs.BindAccountRes bind_account_res = 14;
  if (has_bind_account_res()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      14, this->bind_account_res(), output);
  }

  // optional .ProtoSs.EditPasswordReq edit_password_req = 15;
  if (has_edit_password_req()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      15, this->edit_password_req(), output);
  }

  // optional .ProtoSs.EditPasswordRes edit_password_res = 16;
  if (has_edit_password_res()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      16, this->edit_password_res(), output);
  }

  // optional .ProtoSs.AccountVerifyReq account_verify_req = 17;
  if (has_account_verify_req()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      17, this->account_verify_req(), output);
  }

  // optional .ProtoSs.AccountVerifyRes account_verify_res = 18;
  if (has_account_verify_res()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      18, this->account_verify_res(), output);
  }

  // optional .ProtoSs.GetPlayerDataReq get_player_data_req = 19;
  if (has_get_player_data_req()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      19, this->get_player_data_req(), output);
  }

  // optional .ProtoSs.GetPlayerDataRes get_player_data_res = 20;
  if (has_get_player_data_res()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      20, this->get_player_data_res(), output);
  }

  // optional .ProtoSs.SetPlayerDataReq set_player_data_req = 21;
  if (has_set_player_data_req()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      21, this->set_player_data_req(), output);
  }

  // optional .ProtoSs.SetPlayerDataRes set_player_data_res = 22;
  if (has_set_player_data_res()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      22, this->set_player_data_res(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Msg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .ProtoSs.Head head = 1;
  if (has_head()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->head(), target);
  }

  // optional .ProtoSs.AccountRegReq account_reg_req = 11;
  if (has_account_reg_req()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        11, this->account_reg_req(), target);
  }

  // optional .ProtoSs.AccountRegRes account_reg_res = 12;
  if (has_account_reg_res()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        12, this->account_reg_res(), target);
  }

  // optional .ProtoSs.BindAccountReq bind_account_req = 13;
  if (has_bind_account_req()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        13, this->bind_account_req(), target);
  }

  // optional .ProtoSs.BindAccountRes bind_account_res = 14;
  if (has_bind_account_res()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        14, this->bind_account_res(), target);
  }

  // optional .ProtoSs.EditPasswordReq edit_password_req = 15;
  if (has_edit_password_req()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        15, this->edit_password_req(), target);
  }

  // optional .ProtoSs.EditPasswordRes edit_password_res = 16;
  if (has_edit_password_res()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        16, this->edit_password_res(), target);
  }

  // optional .ProtoSs.AccountVerifyReq account_verify_req = 17;
  if (has_account_verify_req()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        17, this->account_verify_req(), target);
  }

  // optional .ProtoSs.AccountVerifyRes account_verify_res = 18;
  if (has_account_verify_res()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        18, this->account_verify_res(), target);
  }

  // optional .ProtoSs.GetPlayerDataReq get_player_data_req = 19;
  if (has_get_player_data_req()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        19, this->get_player_data_req(), target);
  }

  // optional .ProtoSs.GetPlayerDataRes get_player_data_res = 20;
  if (has_get_player_data_res()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        20, this->get_player_data_res(), target);
  }

  // optional .ProtoSs.SetPlayerDataReq set_player_data_req = 21;
  if (has_set_player_data_req()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        21, this->set_player_data_req(), target);
  }

  // optional .ProtoSs.SetPlayerDataRes set_player_data_res = 22;
  if (has_set_player_data_res()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        22, this->set_player_data_res(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Msg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .ProtoSs.Head head = 1;
    if (has_head()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->head());
    }

    // optional .ProtoSs.AccountRegReq account_reg_req = 11;
    if (has_account_reg_req()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->account_reg_req());
    }

    // optional .ProtoSs.AccountRegRes account_reg_res = 12;
    if (has_account_reg_res()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->account_reg_res());
    }

    // optional .ProtoSs.BindAccountReq bind_account_req = 13;
    if (has_bind_account_req()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->bind_account_req());
    }

    // optional .ProtoSs.BindAccountRes bind_account_res = 14;
    if (has_bind_account_res()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->bind_account_res());
    }

    // optional .ProtoSs.EditPasswordReq edit_password_req = 15;
    if (has_edit_password_req()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->edit_password_req());
    }

    // optional .ProtoSs.EditPasswordRes edit_password_res = 16;
    if (has_edit_password_res()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->edit_password_res());
    }

    // optional .ProtoSs.AccountVerifyReq account_verify_req = 17;
    if (has_account_verify_req()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->account_verify_req());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional .ProtoSs.AccountVerifyRes account_verify_res = 18;
    if (has_account_verify_res()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->account_verify_res());
    }

    // optional .ProtoSs.GetPlayerDataReq get_player_data_req = 19;
    if (has_get_player_data_req()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->get_player_data_req());
    }

    // optional .ProtoSs.GetPlayerDataRes get_player_data_res = 20;
    if (has_get_player_data_res()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->get_player_data_res());
    }

    // optional .ProtoSs.SetPlayerDataReq set_player_data_req = 21;
    if (has_set_player_data_req()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->set_player_data_req());
    }

    // optional .ProtoSs.SetPlayerDataRes set_player_data_res = 22;
    if (has_set_player_data_res()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->set_player_data_res());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Msg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Msg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Msg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Msg::MergeFrom(const Msg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_head()) {
      mutable_head()->::ProtoSs::Head::MergeFrom(from.head());
    }
    if (from.has_account_reg_req()) {
      mutable_account_reg_req()->::ProtoSs::AccountRegReq::MergeFrom(from.account_reg_req());
    }
    if (from.has_account_reg_res()) {
      mutable_account_reg_res()->::ProtoSs::AccountRegRes::MergeFrom(from.account_reg_res());
    }
    if (from.has_bind_account_req()) {
      mutable_bind_account_req()->::ProtoSs::BindAccountReq::MergeFrom(from.bind_account_req());
    }
    if (from.has_bind_account_res()) {
      mutable_bind_account_res()->::ProtoSs::BindAccountRes::MergeFrom(from.bind_account_res());
    }
    if (from.has_edit_password_req()) {
      mutable_edit_password_req()->::ProtoSs::EditPasswordReq::MergeFrom(from.edit_password_req());
    }
    if (from.has_edit_password_res()) {
      mutable_edit_password_res()->::ProtoSs::EditPasswordRes::MergeFrom(from.edit_password_res());
    }
    if (from.has_account_verify_req()) {
      mutable_account_verify_req()->::ProtoSs::AccountVerifyReq::MergeFrom(from.account_verify_req());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_account_verify_res()) {
      mutable_account_verify_res()->::ProtoSs::AccountVerifyRes::MergeFrom(from.account_verify_res());
    }
    if (from.has_get_player_data_req()) {
      mutable_get_player_data_req()->::ProtoSs::GetPlayerDataReq::MergeFrom(from.get_player_data_req());
    }
    if (from.has_get_player_data_res()) {
      mutable_get_player_data_res()->::ProtoSs::GetPlayerDataRes::MergeFrom(from.get_player_data_res());
    }
    if (from.has_set_player_data_req()) {
      mutable_set_player_data_req()->::ProtoSs::SetPlayerDataReq::MergeFrom(from.set_player_data_req());
    }
    if (from.has_set_player_data_res()) {
      mutable_set_player_data_res()->::ProtoSs::SetPlayerDataRes::MergeFrom(from.set_player_data_res());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Msg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Msg::CopyFrom(const Msg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg::IsInitialized() const {

  return true;
}

void Msg::Swap(Msg* other) {
  if (other != this) {
    std::swap(head_, other->head_);
    std::swap(account_reg_req_, other->account_reg_req_);
    std::swap(account_reg_res_, other->account_reg_res_);
    std::swap(bind_account_req_, other->bind_account_req_);
    std::swap(bind_account_res_, other->bind_account_res_);
    std::swap(edit_password_req_, other->edit_password_req_);
    std::swap(edit_password_res_, other->edit_password_res_);
    std::swap(account_verify_req_, other->account_verify_req_);
    std::swap(account_verify_res_, other->account_verify_res_);
    std::swap(get_player_data_req_, other->get_player_data_req_);
    std::swap(get_player_data_res_, other->get_player_data_res_);
    std::swap(set_player_data_req_, other->set_player_data_req_);
    std::swap(set_player_data_res_, other->set_player_data_res_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Msg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Msg_descriptor_;
  metadata.reflection = Msg_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtoSs

// @@protoc_insertion_point(global_scope)
