-- this file is generated by program!
-- don't change it manaully.
-- source file: lord.xls
-- created at: Mon May 26 14:19:35 2014


local res_lord = {}


res_lord.type_map = {}
local type_map = res_lord.type_map
type_map[1001] = "lords"
type_map["lords"] = 1001


res_lord.lords = {}
local lords = res_lord.lords

lords[1] = {
	id = 1001,
	name = "lord",
	exp = 10,
	charm = 10,
	leadership = 10,
	stamina = 10,
	action_force = 180,
}

lords[2] = {
	exp = 20,
	charm = 12,
	leadership = 12,
	stamina = 12,
	action_force = 240,
}

res_lord.all_type= {}
local all_type = res_lord.all_type
all_type[1] = lords



for i=1, #(res_lord.all_type) do
	local item = res_lord.all_type[i]
	for j=1, #item do
		item[j].__index = item[j]
		if j < #item then
			setmetatable(item[j+1], item[j])
		end
	end
end


return res_lord

